language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3"
env:
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1
  - DJANGO_VERSION=2.2
install:
  - "python setup.py install"
  - "pip install -U pip"
  - "pip install django==$DJANGO_VERSION"
  - "pip install tox-travis pillow"
script:
  - tox
  - python manage.py test

matrix:
  include:
    python: "3.7"
    env: DJANGO_VERSION=2.2
    install:
      - "python setup.py install"
      - "pip install -U pip"
      - "pip install django~=$DJANGO_VERSION"
      - "pip install tox-travis pillow"
    script:
      - tox
      - python manage.py test
    after_success:
      - "pip install polib"
      - "python manage.py auto_transrate django_boost --exclude-locale ja --exclude-id username --exclude-id 'email address' --exclude-id 'Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'"
