language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
env:
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1
  - DJANGO_VERSION=2.2
install:
  - "python setup.py install"
  - "pip install -U pip"
  - "pip install django~=$DJANGO_VERSION"
  - "pip install -r tests/requirements.txt"
script:
  - tox
  - "python manage.py auto_migrate_test --remove"
