# Generated by Django 2.2.3 on 2019-08-18 08:54

from django.db import migrations, models
import django.db.models.deletion
import django_boost.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('color', django_boost.models.fields.ColorCodeFiled(max_length=7)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='example.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='deleted_at')),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('tags', models.ManyToManyField(related_name='articles', to='example.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
