# Generated by Django 2.0.13 on 2019-10-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_auto_20190929_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to='img'),
            preserve_default=False,
        ),
    ]
