# Generated by Django 3.0 on 2022-09-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='deleted date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated date'),
        ),
    ]
