# Generated by Django 5.2.15 on 2026-07-04 14:24

import django_boost.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0005_auto_20220907_1507"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="color",
            field=django_boost.models.fields.ColorCodeField(max_length=7, upper=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=django_boost.models.fields.ColorCodeField(max_length=7, upper=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
