# Generated by Django 5.2.15 on 2026-07-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_boost', '0002_auto_20191003_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
