name: "Release with commit"

on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: ChanTsune/release-with-commit@v4.0.1
        id: create_release
        with:
          regexp: "^:bookmark:\\s+Release (\\d+(?:[.]\\d+)*)\n*((?:\\s|\\S)+)"
          regexp_options: "us"
          release_name: "version $1"
          tag_name: "v$1"
          body: "$2"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'
      - uses: actions/checkout@v7
        if: ${{ steps.create_release.outputs.created == 'true' }}
      - name: Install uv
        if: ${{ steps.create_release.outputs.created == 'true' }}
        uses: astral-sh/setup-uv@v7
      - name: Build and publish
        if: ${{ steps.create_release.outputs.created == 'true' }}
        env:
          UV_PUBLISH_USERNAME: ${{ secrets.PYPI_USERNAME }}
          UV_PUBLISH_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          uv build
          uv publish
