name: Test

on:
  push:
  pull_request:
    branches:
    - master

jobs:
  test:
    strategy:
      matrix:
        python-version:
        - '3.8.x'
        - '3.9.x'
        - '3.10.x'
        - '3.11.0-alpha - 3.11.x'
        django-version:
        - '3.0'
        - '3.1'
        - '3.2'
        - '4.0'
    runs-on: ubuntu-latest
    env:
      DJANGO_VERSION: ${{ matrix.django-version }}
    steps:
    - uses: actions/checkout@v2.4.0
    - name: 'Set up Python ${{ matrix.python-version }}'
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python setup.py install
        pip install -U pip
        pip install wheel
        pip install django~=$DJANGO_VERSION
        pip install pillow
        pip install tox-travis
        pip install codecov
    - name: Tox
      run: |
        tox
    - name: Test
      run: |
        coverage run manage.py test
    - name: Report
      run: |
        coverage report
    - name: codecov
      run: |
        codecov
