name: Test

on:
  push:
  pull_request:
    branches:
    - master

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - '3.8.x'
        - '3.9.x'
        - '3.10.x'
        - '3.11.x'
        - '3.12.0-alpha - 3.12.x'
        django-version:
        - '3.0.*'
        - '3.1.*'
        - '3.2.*'
        - '4.0.*'
        - '4.1.*'
        - '4.2.*'
    runs-on: ubuntu-latest
    env:
      DJANGO_VERSION: ${{ matrix.django-version }}
    steps:
    - uses: actions/checkout@v3
    - name: 'Set up Python ${{ matrix.python-version }}'
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: "requirements/ci.txt"
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install -r requirements/ci.txt
        pip install django==$DJANGO_VERSION
        python setup.py install
    - name: Tox
      run: |
        tox
    - name: Test
      run: |
        coverage run manage.py test
    - name: Report
      run: |
        coverage report
    - name: codecov
      run: |
        codecov
